Revert "Add ability to load CreateDirect3DDeviceFromDXGIDevice from d3d11.dll"
This reverts commit 23f60ebe015cdefd017639d3eb826bf058cae141.

Reason for revert: breaks downstream: create_direct3d_device.h(14,10): fatal error: 'windows.graphics.capture.interop.h' file not found

Original change's description:
> Add ability to load CreateDirect3DDeviceFromDXGIDevice from d3d11.dll
>
> Creating a Direct3D11Device from a DXGIDevice is necessary for the new
> WGC based window capturer. However, the
> CreateDirect3DDeviceFromDXGIDevice API is not available on all
> versions of Windows, which means we have to load this function from
> d3d11.dll at runtime.
>
> You can see how this function will be used in this CL:
> 196624: Finish implementing WGC Window Capturer and add unit tests. |
> https://webrtc-review.googlesource.com/c/src/+/196624
>
> I also ensure we don't leak HSTRINGs in GetActivationFactory and fix
> up some includes in ScopedComInitializer.
>
> Bug: webrtc:9273
> Change-Id: Ida240b2c0f637d70ec405de7d8f59f0c12aee1f1
> Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/196622
> Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
> Commit-Queue: Austin Orion <auorion@microsoft.com>
> Cr-Commit-Position: refs/heads/master@{#32984}

TBR=mbonadei@webrtc.org,tommi@webrtc.org,sergeyu@chromium.org,auorion@microsoft.com

Change-Id: If48172db15ff09a10bd32e762ee2c952dc9d9337
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: webrtc:9273