Update patch set 17
Patch Set 17:

Compilation fails after rebase, due to one of my earlier cls making the inherit of the AdaptationObserver interface non-public:

../../rtc_base/ptr_util.h:64:35: error: cannot cast 'webrtc::VideoStreamEncoder' to its protected base class 'webrtc::AdaptationObserverInterface'
  return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
                                  ^
../../video/video_stream_encoder.cc:633:16: note: in instantiation of function template specialization 'rtc::MakeUnique<webrtc::QualityScaler, webrtc::VideoStreamEncoder *, const webrtc::VideoEncoder::QpThresholds &>' requested here
          rtc::MakeUnique<QualityScaler>(this, *(scaling_settings.thresholds));
               ^
../../video/video_stream_encoder.h:53:28: note: declared protected here
                           protected AdaptationObserverInterface {
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

It seems I can fix that with a static_cast,

--- a/video/video_stream_encoder.cc
+++ b/video/video_stream_encoder.cc
@@ -630,7 +630,9 @@ void VideoStreamEncoder::ConfigureQualityScaler() {
       // Quality scaler has not already been configured.
       // Drop frames and scale down until desired quality is achieved.
       quality_scaler_ =
-          rtc::MakeUnique<QualityScaler>(this, *(scaling_settings.thresholds));
+          rtc::MakeUnique<QualityScaler>(
+              static_cast<AdaptationObserverInterface*>(this),
+              *(scaling_settings.thresholds));
     }
   } else {
     quality_scaler_.reset(nullptr);

Is that the right way?

Patch-set: 17
Reviewer: Gerrit User 5234 <5234@58829da1-049c-39fb-b951-ebdcd0984767>