Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.webrtc.try/win_x86_msvc_rel JOB_FAILED https://cr-buildbucket.appspot.com/build/8839203358147482000
    #### Step _compile_ failed. Error logs are shown below:
    ```
    [3/68] CXX obj/test/pc/e2e/default_video_quality_analyzer/default_video_quality_analyzer.obj
    FAILED: obj/test/pc/e2e/default_video_quality_analyzer/default_video_quality_analyzer.obj
    ninja -t msvc -e environment.x86 -- "C:\b\s\w\ir\cache\builder\src\third_party\depot_tools\win_toolc...(too long)
    ../../test/pc/e2e/analyzer/video/default_video_quality_analyzer.cc(367): error C7555: use of designated initializers requires at least '/std:c++latest'
    ../../test/pc/e2e/analyzer/video/default_video_quality_analyzer.cc(440): error C7555: use of designated initializers requires at least '/std:c++latest'
    ```
    #### More information in raw_io.output[failure_summary]

Patch-set: 3
Tag: autogenerated:cv